-- AlterTable
ALTER TABLE `verification_sessions` MODIFY `status` ENUM('VERIFICATION_IN_PROGRESS', 'VERIFIED', 'VERIFICATION_FAILED', 'LOCKED', 'SUPERSEDED') NOT NULL DEFAULT 'VERIFICATION_IN_PROGRESS';

